language: node_js

node_js:
  - node

branches:
  only:
    - master

cahce:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

script:
  - yarn test

after_success:
  - yarn test:report
  - yarn test:coverage
